### ISSUE TITLE
Flatten step potentially creates corrupted avro records

### ISSUE THREAD

**Issue by nicoloboschi** [datastax/pulsar-transformations#33]
To reproduce: (in docker env) 

docker-compose.yaml
```
postgres:
    image: postgres:14.3
    container_name: postgres
    networks: [ "net1" ]
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
```

1. Setup postgre debezium source with avro converter
```
docker-compose up -d postgres

docker exec -it postgres psql -U postgres -c 'create table if not exists pulsar_table_source (key VARCHAR(255) PRIMARY KEY, value VARCHAR(255) NULL);' postgres



docker exec -it pulsar bin/pulsar-admin sources create --namespace default --tenant public \
    --source-type  debezium-postgres \
    --destination-topic-name debezium-postgres-topic \
    --name pg-source \
    --source-config '{"key.converter": "org.apache.pulsar.kafka.shade.io.confluent.connect.avro.AvroConverter", "value.converter": "org.apache.pulsar.kafka.shade.io.confluent.connect.avro.AvroConverter", "plugin.name": "pgoutput","database.hostname": "postgres", "database.user": "postgres", "database.server.name": "dbserver1", "database.password": "password", "database.dbname": "postgres", "schema.whitelist": "public", "pulsar.service.url": "pulsar://pulsar:6650" }' \
    --parallelism 1

docker exec -it postgres bash -c "psql -U postgres -c \"insert into pulsar_source_table(key,value) select left(md5(i::text), 10),i from generate_series(1, 10) s(i)\""

```

2. Create a sink (in my case a Pulsar Sink) with the transforms fn attached
```
docker exec -it pulsar bin/pulsar-admin sinks create --namespace default --tenant public \
    --sink-type cassandra-enhanced \
    --name cassandra-sink \
    --inputs dbserver1.public.pulsar_source_table \
    --subs-position Earliest \
    --sink-config '{"verbose": true, "tasks.max":1,"topics":"dbserver1.public.pulsar_source_table","contactPoints":"cassandra","loadBalancing.localDc":"datacenter1","port":9042,"cloud.secureConnectBundle":null,"ignoreErrors":"None","maxConcurrentRequests":500,"maxNumberOfRecordsInBatch":32,"queryExecutionTimeout":30,"connectionPoolLocalSize":4,"jmx":true,"compression":"None","auth":{"provider":"None","username":null,"password":null,"gssapi":{"keyTab":null,"principal":null,"service":"dse"}},"ssl":{"provider":"None","hostnameValidation":true,"keystore":{"password":null,"path":null},"openssl":{"keyCertChain":null,"privateKey":null},"truststore":{"password":null,"path":null},"cipherSuites":null},"topic":{"dbserver1.public.pulsar_source_table":{"baselines":{"pgsourcetable":{"mapping":"key=key.key, value=value.myvalue","consistencyLevel":"LOCAL_ONE","ttl":-1,"ttlTimeUnit":"SECONDS","timestampTimeUnit":"MICROSECONDS","nullToUnset":true,"deletesEnabled":true}},"codec":{"locale":"en_US","timeZone":"UTC","timestamp":"CQL_TIMESTAMP","date":"ISO_LOCAL_DATE","time":"ISO_LOCAL_TIME","unit":"MILLISECONDS"}}}}' \
    --parallelism 1 \
    --transform-function builtin://transform \
    --transform-function-config '{"steps": [{"type": "flatten", "part": "value"}]}'
```
Then you get this error in the sink
```
org.apache.pulsar.client.api.SchemaSerializationException: java.io.EOFException
        at org.apache.pulsar.client.impl.schema.generic.GenericAvroReader.read(GenericAvroReader.java:91) ~[?:?]
        at org.apache.pulsar.client.impl.schema.generic.GenericAvroReader.read(GenericAvroReader.java:41) ~[?:?]
        at org.apache.pulsar.client.api.schema.SchemaReader.read(SchemaReader.java:40) ~[java-instance.jar:?]
        at org.apache.pulsar.client.impl.schema.reader.AbstractMultiVersionReader.read(AbstractMultiVersionReader.java:89) ~[?:?]
        at org.apache.pulsar.client.impl.schema.AbstractStructSchema.decode(AbstractStructSchema.java:66) ~[?:?]
        at org.apache.pulsar.client.impl.schema.KeyValueSchemaImpl.decode(KeyValueSchemaImpl.java:180) ~[?:?]
        at org.apache.pulsar.client.impl.schema.KeyValueSchemaImpl.lambda$decode$0(KeyValueSchemaImpl.java:161) ~[?:?]
        at org.apache.pulsar.common.schema.KeyValue.decode(KeyValue.java:146) ~[java-instance.jar:?]
        at org.apache.pulsar.client.impl.schema.KeyValueSchemaImpl.decode(KeyValueSchemaImpl.java:161) ~[?:?]
        at org.apache.pulsar.client.impl.schema.KeyValueSchemaImpl.decode(KeyValueSchemaImpl.java:43) ~[?:?]
        at org.apache.pulsar.client.impl.schema.AutoConsumeSchema.decode(AutoConsumeSchema.java:120) ~[?:?]
        at org.apache.pulsar.client.impl.schema.AutoConsumeSchema.decode(AutoConsumeSchema.java:48) ~[?:?]
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.encodeWithRecordSchemaAndDecodeWithSinkSchema(JavaInstanceRunnable.java:459) ~[?:?]
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.sendOutputMessage(JavaInstanceRunnable.java:416) ~[?:?]
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.handleResult(JavaInstanceRunnable.java:394) ~[?:?]
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.run(JavaInstanceRunnable.java:335) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: java.io.EOFException
        at [org.apache.avro.io](http://org.apache.avro.io/).BinaryDecoder$ByteArrayByteSource.readRaw(BinaryDecoder.java:999) ~[java-instance.jar:?]
        at [org.apache.avro.io](http://org.apache.avro.io/).BinaryDecoder.doReadBytes(BinaryDecoder.java:405) ~[java-instance.jar:?]
        at [org.apache.avro.io](http://org.apache.avro.io/).BinaryDecoder.readString(BinaryDecoder.java:313) ~[java-instance.jar:?]
        at [org.apache.avro.io](http://org.apache.avro.io/).ResolvingDecoder.readString(ResolvingDecoder.java:208) ~[java-instance.jar:?]
        at org.apache.avro.generic.GenericDatumReader.readString(GenericDatumReader.java:469) ~[java-instance.jar:?]
        at org.apache.avro.generic.GenericDatumReader.readString(GenericDatumReader.java:459) ~[java-instance.jar:?]
        at org.apache.avro.generic.GenericDatumReader.readWithoutConversion(GenericDatumReader.java:191) ~[java-instance.jar:?]
        at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:160) ~[java-instance.jar:?]
        at org.apache.avro.generic.GenericDatumReader.readField(GenericDatumReader.java:259) ~[java-instance.jar:?]
        at org.apache.avro.generic.GenericDatumReader.readRecord(GenericDatumReader.java:247) ~[java-instance.jar:?]
        at org.apache.avro.generic.GenericDatumReader.readWithoutConversion(GenericDatumReader.java:179) ~[java-instance.jar:?]
        at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:160) ~[java-instance.jar:?]
        at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:153) ~[java-instance.jar:?]
        at org.apache.pulsar.client.impl.schema.generic.GenericAvroReader.read(GenericAvroReader.java:86) ~[?:?]
        ... 16 more
```

Notes:
1. If I remove the transform function, the sink is able to read the record coming from the debezium source
2. I use the Avro format because JSON is not supported by the flatten step (perhaps we should track an issue)
3. My first assumption is that the output schema is not keeping the schema props. the debezium source set a special prop "__AVRO_READ_OFFSET__" to 5. This is used in Pulsar to set the start offset for reading the record. I don't know why and it may cause such error btw

**Comment by aymkhalil** [comment]
The flatten schema does actually retain the props - this is done by the `Field` [constructor](https://github.com/datastax/pulsar-transformations/blob/7673a3fe9347b794891a5d96f1660b3470b9ec9c/pulsar-transformations/src/main/java/com/datastax/oss/pulsar/functions/transforms/FlattenStep.java#L138) that takes the old schema (which contains the props) 

I found (accidentally) a bug with aliases though not being copied over. will try to reproduce and troubleshoot more the above error.

**Comment by aymkhalil** [comment]
probably the `__AVRO_READ_OFFSET__` value itself is not valid anymore and needs adjustment...

**Comment by aymkhalil** [comment]
I actually found multiple issues:
1. The props where only copied on the fields schema level but not at the top schema level. However, copying the `__AVRO_READ_OFFSET__` actually causes issue on the flatten transform when used in combo with debezium
2. flatten field didn't handle nullability correctly - if a an parent field is null, it should mark the flattened field as nullable regardless of its nullability status in the original schema 
3. flatten was relying on reflection on the GenericRecord to traverse the recursion tree - this cause the schema levels to be trimmed prematurely in the recursion tree. Instead, it should rely on the original schema

**Comment by aymkhalil** [comment]
with #34 , I'm able to generate record in C* sink from debezium source with the following config:

```
bin/pulsar-admin sinks localrun \
 --archive /Users/ayman.khalil/workplace/datastax/pulsar-sink/pulsar-dist/target/cassandra-enhanced-pulsar-sink-1.6.7-SNAPSHOT-nar.nar --name flatten-sink --inputs dbserver1.public.pulsar_table_source \
    --subs-position Earliest \
    --sink-config '{"verbose": true, "tasks.max":1,"topics":"dbserver1.public.pulsar_table_source","contactPoints":"localhost","loadBalancing.localDc":"Cassandra","port":9042,"maxConcurrentRequests":500,"maxNumberOfRecordsInBatch":32,"queryExecutionTimeout":30,"connectionPoolLocalSize":4,"jmx":true,"compression":"None","auth":{"provider":"None","username":null,"password":null,"gssapi":{"keyTab":null,"principalz":null,"service":"dse"}},"ssl":{"provider":"None","hostnameValidation":true,"keystore":{"password":null,"path":null},"openssl":{"keyCertChain":null,"privateKey":null},"truststore":{"password":null,"path":null},"cipherSuites":null},"topic":{"dbserver1.public.pulsar_table_source":{"ks1":{"pgsourcetable":{"mapping":"key=key.key,value=value.after_value","consistencyLevel":"LOCAL_ONE","ttl":-1,"ttlTimeUnit":"SECONDS","timestampTimeUnit":"MICROSECONDS","nullToUnset":true,"deletesEnabled":true}},"codec":{"locale":"en_US","timeZone":"UTC","timestamp":"CQL_TIMESTAMP","date":"ISO_LOCAL_DATE","time":"ISO_LOCAL_TIME","unit":"MILLISECONDS"}}}}' \
    --parallelism 1 --transform-function /Users/ayman.khalil/workplace/datastax/pulsar-transformations/pulsar-transformations/target/pulsar-transformations-2.0.2-SNAPSHOT.nar  \
    --transform-function-config '{"steps": [{"type": "flatten"}]}'
```

The important pars are the flatten doesn't pass a part (works on both key and value):
```
{"steps": [{"type": "flatten"}]}
```

and the mapping of the value is:
```
key=key.key,value=value.after_value
```
