### ISSUE TITLE
[compute] Cannot convert Avro Utf8 string to INT32

### ISSUE THREAD

**Issue by nicoloboschi** [datastax/pulsar-transformations#62]
I have the input schema which is key-value with avro's value with a text field (`myvalue`). I want to convert it to INT (I assume that it's a valid number). This is my config for the function:
```
{"steps":[{"type":"compute","fields": 
       {"name":"value.value","expression":"value.myvalue","type":"INT32"}
]}
```

I'm getting this error
```
jakarta.el.ELException: Cannot convert [13360] of type [class org.apache.avro.util.Utf8] to [class java.lang.Integer]
	at org.apache.el.lang.ELSupport.coerceToNumber(ELSupport.java:390) ~[?:?]
	at org.apache.el.lang.ELSupport.coerceToType(ELSupport.java:532) ~[?:?]
	at org.apache.el.ExpressionFactoryImpl.coerceToType(ExpressionFactoryImpl.java:46) ~[?:?]
	at jakarta.el.ELContext.convertToType(ELContext.java:320) ~[?:?]
	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:192) ~[?:?]
	at com.datastax.oss.pulsar.functions.transforms.jstl.JstlEvaluator.evaluate(JstlEvaluator.java:119) ~[?:?]
	at com.datastax.oss.pulsar.functions.transforms.ComputeStep.computeFields(ComputeStep.java:250) ~[?:?]
	at com.datastax.oss.pulsar.functions.transforms.ComputeStep.computeValueFields(ComputeStep.java:86) ~[?:?]
	at com.datastax.oss.pulsar.functions.transforms.ComputeStep.process(ComputeStep.java:69) ~[?:?]
	at com.datastax.oss.pulsar.functions.transforms.TransformFunction.process(TransformFunction.java:261) ~[?:?]
	at com.datastax.oss.pulsar.functions.transforms.TransformFunction.process(TransformFunction.java:251) ~[?:?]
	at com.datastax.oss.pulsar.functions.transforms.TransformFunction.process(TransformFunction.java:123) ~[?:?]
	at org.apache.pulsar.functions.instance.JavaInstance.handleMessage(JavaInstance.java:94) ~[com.datastax.oss-pulsar-functions-instance-2.10.3.2.jar:2.10.3.2]
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.run(JavaInstanceRunnable.java:321) ~[com.datastax.oss-pulsar-functions-instance-2.10.3.2.jar:2.10.3.2]
```

I'm using 2.1.0
I'm 99% sure it was working before with 2.0.2

Maybe I should switch to the cast function?

**Comment by nicoloboschi** [comment]
Fixed by #63
